version: "2"
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports: 
            - "${PORT}:${PORT}"
        environment:
            - PORT=${PORT}
        networks:
            - default
    www:
        image: nginx
        env_file:
            - .env
        depends_on:
            - api
        ports: 
            - "80:80"
        volumes:
            - ./html:/usr/share/nginx/html
            - ./nginx/conf.d:/etc/nginx/conf.d

        networks:
            - default
volumes:
    persistent: